sudo: required

services:
  - docker

install:
  - bash docker/build

before_script:
  - gem install rake
  - bundle

script:
  - bundle exec rubocop -F
  - docker run --rm -i hadolint/hadolint < Dockerfile
  - rake

deploy:
  provider: script
  script: bash docker/push
  on:
    branch: master
