sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - gem install rake
  - bash docker/build

script:
  - rake

deploy:
  provider: script
  script: bash docker/push
  on:
    branch: master
