name: test, docker build & push

on: [push]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -i hadolint/hadolint < Dockerfile

  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rubocop -F
      - run: bundle exec yard doc --fail-on-warning --no-output

  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rspec

  docker-test:
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          bundle exec rake

  docker-push:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - docker-test
      - hadolint
      - ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bin/docker-build

      - run: bin/docker-push
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
